# Generated by Django 2.1.1 on 2019-07-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_entered',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_deleted',
            new_name='deleted_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_modified',
            new_name='modified_date',
        ),
    ]
